### PR TITLE
README.md modified from ggpark

### PR DESCRIPTION
**Pull request by ggpark1218**

### CODE REVIEW

**Comment by SeoYeonJu4382** [comment]
could you please send more detail information?

**Comment by ggpark1218** [comment]
I've added this information.

**Comment by youngjae0603** [comment]
thank you! can you make new txt file about introduction of yourself??

**Comment by ggpark1218** [comment]
This is introduction of myself! Thank you :)

**Comment by ggpark1218** [comment]
Thank you !!

**Pull request merged**
